package nl.sebastiaanvogels.sonosmp3player;

import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.provider.OpenableColumns;import android.database.Cursor;import android.net.wifi.WifiManager;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;import javax.xml.parsers.*;import org.w3c.dom.*;import fi.iki.elonen.NanoHTTPD;

public class MainActivity extends Activity {
  LinearLayout list; ArrayList<File> songs=new ArrayList<>(); SonosServer server; SonosDevice arc; WifiManager.MulticastLock multicastLock;
  public void onCreate(Bundle b){super.onCreate(b);build();try{server=new SonosServer();server.start(NanoHTTPD.SOCKET_READ_TIMEOUT,false);}catch(Exception e){toast("Lokale server kon niet starten");}discover();}
  void build(){ScrollView s=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(32,32,32,32);TextView title=new TextView(this);title.setText("🔊 Sonos MP3 Player");title.setTextSize(28);title.setPadding(0,0,0,24);list.addView(title);Button find=new Button(this);find.setText("🔎 Zoek Sonos Arc");find.setOnClickListener(v->discover());list.addView(find);Button add=new Button(this);add.setText("➕ MP3 toevoegen");add.setOnClickListener(v->pick());list.addView(add);TextView info=new TextView(this);info.setText("Telefoon en Sonos moeten op hetzelfde wifi-netwerk zitten.");info.setPadding(0,16,0,16);list.addView(info);s.addView(list);setContentView(s);}
  void discover(){new Thread(()->{try{WifiManager wm=(WifiManager)getApplicationContext().getSystemService(WIFI_SERVICE);multicastLock=wm.createMulticastLock("sonos-discovery");multicastLock.setReferenceCounted(false);multicastLock.acquire();arc=Sonos.discover();if(multicastLock.isHeld())multicastLock.release();runOnUiThread(()->toast(arc==null?"Geen Sonos Arc gevonden":"Gevonden: "+arc.name));}catch(Exception e){try{if(multicastLock!=null&&multicastLock.isHeld())multicastLock.release();}catch(Exception ignored){}runOnUiThread(()->toast("Sonos zoeken mislukt: "+e.getMessage()));}}).start();}
  void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("audio/mpeg");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,false);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,7);}
  protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==7&&c==RESULT_OK&&d!=null){try{Uri u=d.getData();String name="song.mp3";Cursor q=getContentResolver().query(u,null,null,null,null);if(q!=null){int n=q.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(q.moveToFirst()&&n>=0)name=q.getString(n);q.close();}File f=new File(getFilesDir(),System.currentTimeMillis()+"-"+name.replaceAll("[^a-zA-Z0-9._-]","_"));try(InputStream in=getContentResolver().openInputStream(u);OutputStream out=new FileOutputStream(f)){byte[] x=new byte[8192];int n;while((n=in.read(x))>0)out.write(x,0,n);}songs.add(f);addSong(f);}catch(Exception e){toast("MP3 toevoegen mislukt: "+e.getMessage());}}}
  void addSong(File f){Button b=new Button(this);b.setText("▶️ "+f.getName());b.setOnClickListener(v->new Thread(()->{try{if(arc==null)arc=Sonos.discover();if(arc==null)throw new Exception("Geen Sonos Arc gevonden");String ip=localIp();if(ip.equals("127.0.0.1"))throw new Exception("Geen wifi-IP gevonden");String uri="http://"+ip+":"+server.getListeningPort()+"/"+URLEncoder.encode(f.getName(),"UTF-8").replace("+","%20");Sonos.play(arc,uri);runOnUiThread(()->toast("Afspelen op "+arc.name));}catch(Exception e){runOnUiThread(()->toast("Afspelen mislukt: "+e.getMessage()));}}).start());list.addView(b);}
  String localIp(){try{Enumeration<NetworkInterface> es=NetworkInterface.getNetworkInterfaces();while(es.hasMoreElements()){NetworkInterface ni=es.nextElement();if(!ni.isUp()||ni.isLoopback())continue;for(InterfaceAddress a:ni.getInterfaceAddresses()){InetAddress x=a.getAddress();if(x instanceof Inet4Address&&!x.isLoopbackAddress()&&!x.isLinkLocalAddress())return x.getHostAddress();}}}catch(Exception ignored){}return "127.0.0.1";}
  void toast(String x){Toast.makeText(this,x,Toast.LENGTH_LONG).show();}
  class SonosServer extends NanoHTTPD {SonosServer()throws IOException{super(0);}public Response serve(IHTTPSession q){try{String p=URLDecoder.decode(q.getUri().substring(1),"UTF-8");for(File f:songs)if(f.getName().equals(p)){long len=f.length();String range=q.getHeaders().get("range");long start=0,end=len-1;if(range!=null&&range.startsWith("bytes=")){String z=range.substring(6).split("-")[0];if(!z.isEmpty())start=Long.parseLong(z);if(start>=len) return newFixedLengthResponse(Response.Status.RANGE_NOT_SATISFIABLE,"text/plain","");}end=Math.min(end,len-1);long count=end-start+1;FileInputStream in=new FileInputStream(f);in.skip(start);Response r=newFixedLengthResponse(range==null?Response.Status.OK:Response.Status.PARTIAL_CONTENT,"audio/mpeg",in,count);r.addHeader("Accept-Ranges","bytes");r.addHeader("Content-Length",String.valueOf(count));if(range!=null)r.addHeader("Content-Range","bytes "+start+"-"+end+"/"+len);return r;}return newFixedLengthResponse(Response.Status.NOT_FOUND,"text/plain","Not found");}catch(Exception e){return newFixedLengthResponse(Response.Status.INTERNAL_ERROR,"text/plain","Error: "+e.getMessage());}}}
}

class SonosDevice{String name,control;SonosDevice(String n,String c){name=n;control=c;}}
class Sonos{
 static SonosDevice discover()throws Exception{DatagramSocket s=new DatagramSocket();s.setReuseAddress(true);s.setSoTimeout(1200);String m="M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: \"ssdp:discover\"\r\nMX: 1\r\nST: urn:schemas-upnp-org:device:ZonePlayer:1\r\n\r\n";byte[] out=m.getBytes("US-ASCII");s.send(new DatagramPacket(out,out.length,InetAddress.getByName("239.255.255.250"),1900));byte[] b=new byte[8192];while(true){try{DatagramPacket p=new DatagramPacket(b,b.length);s.receive(p);String r=new String(p.getData(),0,p.getLength(),"UTF-8");String loc=null;for(String line:r.split("\\r?\\n"))if(line.toLowerCase(Locale.US).startsWith("location:"))loc=line.substring(9).trim();if(loc!=null){String xml=http(loc);String name=tag(xml,"friendlyName");String control=findAvTransportControl(xml,loc);if(control!=null&&(name.toLowerCase(Locale.US).contains("arc")||name.toLowerCase(Locale.US).contains("sonos")))return new SonosDevice(name,control);}}catch(SocketTimeoutException e){break;}}s.close();return null;}
 static String findAvTransportControl(String xml,String loc)throws Exception{DocumentBuilderFactory f=DocumentBuilderFactory.newInstance();f.setNamespaceAware(false);Document doc=f.newDocumentBuilder().parse(new ByteArrayInputStream(xml.getBytes("UTF-8")));NodeList services=doc.getElementsByTagName("service");for(int i=0;i<services.getLength();i++){Element e=(Element)services.item(i);String st=tag(e,"serviceType");if(st.contains(":AVTransport:")){String cu=tag(e,"controlURL");return new URL(new URL(loc),cu).toString();}}return null;}
 static String http(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(2000);c.setReadTimeout(2000);return read(c.getInputStream());}
 static String tag(String x,String t){int a=x.indexOf("<"+t+">");int b=x.indexOf("</"+t+">");return a>=0&&b>a?x.substring(a+t.length()+2,b).trim():"";}
 static String tag(Element e,String t){NodeList n=e.getElementsByTagName(t);return n.getLength()>0?n.item(0).getTextContent().trim():"";}
 static String read(InputStream i)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[4096];int n;while((n=i.read(b))>0)o.write(b,0,n);i.close();return o.toString("UTF-8");}
 static void play(SonosDevice d,String uri)throws Exception{String body="<?xml version=\"1.0\"?><s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><s:Body><u:SetAVTransportURI xmlns:u=\"urn:schemas-upnp-org:service:AVTransport:1\"><InstanceID>0</InstanceID><CurrentURI>"+xml(uri)+"</CurrentURI><CurrentURIMetaData></CurrentURIMetaData></u:SetAVTransportURI></s:Body></s:Envelope>";soap(d.control,body,"urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI");String play="<?xml version=\"1.0\"?><s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><u:Play xmlns:u=\"urn:schemas-upnp-org:service:AVTransport:1\"><InstanceID>0</InstanceID><Speed>1</Speed></u:Play></s:Body></s:Envelope>";soap(d.control,play,"urn:schemas-upnp-org:service:AVTransport:1#Play");}
 static String xml(String x){return x.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&apos;");}
 static void soap(String u,String body,String action)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(3000);c.setReadTimeout(5000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","text/xml; charset=\"utf-8\"");c.setRequestProperty("SOAPAction","\""+action+"\"");byte[] data=body.getBytes("UTF-8");c.setFixedLengthStreamingMode(data.length);c.getOutputStream().write(data);int code=c.getResponseCode();if(code>=300){InputStream er=c.getErrorStream();String msg=er==null?"":read(er);throw new IOException("Sonos HTTP "+code+" "+msg);}c.getInputStream().close();}
}
