plugins {
    id 'com.android.application'
}

android {
    namespace 'nl.sebastiaanvogels.sonosmp3player'
    compileSdk 35
    defaultConfig {
        applicationId 'nl.sebastiaanvogels.sonosmp3player'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
}
